#' 2-Sample Proportions Confidence Interval
#'
#' @description
#' Constructs a confidence interval for the difference between two population
#' proportions (\eqn{\pi_1 - \pi_2}) using one of three methods: the 2SD
#' simulation method, a general simulation method, or a theory-based approach.
#'
#' This function accepts input in **two ways**:
#'
#' - **Summary Statistics:** You already know the number of successes and
#'   sample sizes for both groups. Pass `success_1`, `n_1`, `success_2`,
#'   and `n_2` directly. Note that `method = "2SD"` and
#'   `method = "simulation"` are not available with summary statistics.
#'
#' - **Raw Data:** You have an actual dataset loaded into R. Pass `formula`,
#'   `data`, and `success_level` instead, and the function counts successes
#'   for you automatically. All three methods are available with raw data.
#'
#' @param success_1 A whole number representing the count of successes in
#'   Group 1. For example, if 45 out of 100 patients recovered,
#'   `success_1 = 45`.
#'   **Only used when NOT providing `formula` and `data`.**
#' @param n_1 The sample size of Group 1.
#'   **Only used when NOT providing `formula` and `data`.**
#' @param success_2 A whole number representing the count of successes in
#'   Group 2.
#'   **Only used when NOT providing `formula` and `data`.**
#' @param n_2 The sample size of Group 2.
#'   **Only used when NOT providing `formula` and `data`.**
#' @param group_names A character vector of length 2 giving meaningful names
#'   to the two groups. For example,
#'   `group_names = c("Treatment", "Control")`.
#'   Defaults to `c("Group 1", "Group 2")`. When using raw data, group
#'   names are extracted automatically from the grouping variable.
#'   **Only used when NOT providing `formula` and `data`.**
#' @param formula A two-sided formula of the form `Response ~ Group`
#'   identifying the categorical response variable and the grouping
#'   variable in your dataset. For example,
#'   `formula = Recovered ~ Treatment`.
#'   **Only used when NOT providing summary statistics.**
#' @param data A data frame (loaded from a `.csv`, `.txt`, or `.xlsx` file)
#'   containing the variables named in `formula`.
#'   **Only used when NOT providing summary statistics.**
#' @param success_level A character string specifying which value of the
#'   response variable counts as a "success". For example, if the response
#'   variable contains `"Yes"` and `"No"`, use `success_level = "Yes"`.
#'   **Required when using `formula` and `data`.**
#' @param conf_level The desired confidence level as a decimal. Default is
#'   `0.95` for a 95% confidence interval. Common choices are `0.90`,
#'   `0.95`, and `0.99`. Note that `method = "2SD"` only works at `0.95`.
#' @param method The method used to construct the confidence interval.
#'   Must be one of:
#'   \describe{
#'     \item{`"2SD"`}{(default) The 2SD Simulation Method. An independent bootstrap is generated by resampling with replacement from each group separately.The interval
#'       is \eqn{(\hat{p}_1 - \hat{p}_2) \pm 2 \times SD}. Only valid for 95% confidence interval limit. If you
#'       need a different confidence level, use `method = "simulation"`.}
#'     \item{`"simulation"`}{The Bootstrap Simulation Method. Same
#'       independent bootstrap as 2SD, but uses the middle `conf_level`% of
#'       the simulated distribution to find the bounds. Works for any
#'       confidence level.}
#'     \item{`"theory"`}{The Theory-Based Method. Uses the unpooled
#'       standard error formula and the appropriate Z* multiplier.
#'       Works for any confidence level and with both summary statistics
#'       and raw data.}
#'   }
#' @param sim_reps The number of bootstrap samples when `method = "2SD"`
#'   or `method = "simulation"`. Default is `1000`. Increasing to `5000`
#'   gives a more stable interval.
#'
#' @return An S3 object of class `stat218_2prop_ci` containing all computed
#'   values. You can use the following methods on the result:
#'   \describe{
#'     \item{`print(result)`}{Displays a clean summary of the interval
#'       including both group proportions, the observed difference, SD of
#'       sampling distribution, and the interval bounds.}
#'     \item{`plot(result)`}{Shows the bootstrap or theoretical
#'       distribution with the confidence interval shaded and labeled,
#'       a forest plot of the interval, and a beautified 2x2 contingency
#'       table.}
#'     \item{`plot_steps(result)`}{Displays a detailed three-panel
#'       step-by-step construction of the interval with proper fraction
#'       notation.}
#'   }
#'
#' @details
#' ## The Core Idea
#' A two-sample proportion confidence interval gives a range of plausible
#' values for the true difference \eqn{\pi_1 - \pi_2}. A positive interval
#' suggests Group 1 has a higher proportion; a negative interval suggests
#' Group 2 is higher; an interval containing zero is consistent with no
#' difference between the two groups.
#'
#' ## The 2SD Method
#' An independent bootstrap where successes and failures from each group
#' are resampled with replacement separately. The difference in simulated
#' proportions is recorded for each repetition. The SD of those differences
#' estimates the SE, and the interval is point estimate \eqn{\pm 2 \times SD}.
#' Note that unlike `test_2prop` which uses a permutation approach, the CI
#' bootstrap resamples each group independently -- this is correct for
#' confidence intervals where we are not assuming the null hypothesis.
#'
#' ## Theory Method
#' Uses the **unpooled** standard error (unlike the hypothesis test which
#' uses a pooled proportion). This is because for a confidence interval we
#' are not assuming the two proportions are equal:
#' \deqn{SE = \sqrt{\frac{\hat{p}_1(1-\hat{p}_1)}{n_1} +
#' \frac{\hat{p}_2(1-\hat{p}_2)}{n_2}}}
#'
#' ## Validity Conditions for Theory Method
#' All four cells in the 2x2 contingency table must have at least 10
#' observations:
#' - Successes in Group 1 \eqn{\geq 10}
#' - Failures in Group 1 \eqn{\geq 10}
#' - Successes in Group 2 \eqn{\geq 10}
#' - Failures in Group 2 \eqn{\geq 10}
#'
#' @examples
#' # --- Summary Statistics (theory, default) ---
#' result <- ci_2prop(
#'   success_1 = 45, n_1 = 100,
#'   success_2 = 25, n_2 = 100,
#'   group_names = c("Treatment", "Control"),
#'   method = "theory"
#' )
#' print(result)
#' \dontrun{
#' plot(result)
#' plot_steps(result)
#'}
#'
#' # --- Summary Statistics (theory, 90% CI) ---
#' result2 <- ci_2prop(
#'   success_1 = 45, n_1 = 100,
#'   success_2 = 25, n_2 = 100,
#'   group_names = c("Treatment", "Control"),
#'   conf_level = 0.90, method = "theory"
#' )
#' print(result2)
#' \dontrun{
#' plot(result2)
#' plot_steps(result2)
#'}
#'
#' # --- Raw Data (2SD method) ---
#' car_data <- mtcars
#' car_data$transmission <- ifelse(mtcars$am == 1, "Manual", "Automatic")
#' car_data$engine <- ifelse(mtcars$vs == 1, "Straight", "V-shaped")
#' result3 <- ci_2prop(
#'   formula = transmission ~ engine, data = car_data,
#'   success_level = "Manual", method = "2SD"
#' )
#' print(result3)
#'\dontrun{
#' plot(result3)
#' plot_steps(result3)
#'}
#'
#' # --- Raw Data (simulation, 90% CI) ---
#' result4 <- ci_2prop(
#'   formula = transmission ~ engine, data = car_data,
#'   success_level = "Manual", conf_level = 0.90,
#'   method = "simulation"
#' )
#' print(result4)
#' \dontrun{
#' plot(result4)
#' plot_steps(result4)
#'}
#'
#' # --- Raw Data (theory) ---
#' result5 <- ci_2prop(
#'   formula = transmission ~ engine, data = car_data,
#'   success_level = "Manual", method = "theory"
#' )
#' print(result5)
#' \dontrun{
#' plot(result5)
#' plot_steps(result5)
#'}
#'
#' @export
ci_2prop <- function(success_1 = NULL, n_1 = NULL,
                     success_2 = NULL, n_2 = NULL,
                     group_names = NULL,
                     formula = NULL, data = NULL,
                     success_level = NULL,
                     conf_level = 0.95,
                     method = "2SD",
                     sim_reps = 1000) {

  # ============================================================
  # ROUTING STATION -- Phase Two dual-input logic
  # ============================================================

  summary_stat_provided <- !is.null(success_1) || !is.null(n_1) ||
    !is.null(success_2) || !is.null(n_2)
  formula_provided      <- !is.null(formula) || !is.null(data)

  # Case 1: Both paths provided
  if (summary_stat_provided && formula_provided) {
    cli::cli_abort(c(
      "x" = "You provided both a dataset {.emph (formula/data)} and summary statistics {.emph (success_1/n_1/success_2/n_2)}.",
      "i" = "These are two different ways to use {.fn ci_2prop} -- please choose one:",
      " " = " ",
      "*" = "If you have {.strong raw data}: use {.arg formula}, {.arg data}, and {.arg success_level}, and remove the summary stat arguments.",
      "*" = "If you only have {.strong summary statistics}: use {.arg success_1}, {.arg n_1}, {.arg success_2}, and {.arg n_2}, and remove {.arg formula} and {.arg data}."
    ))
  }

  # Case 4: Neither path provided
  if (!summary_stat_provided && !formula_provided) {
    cli::cli_abort(c(
      "x" = "No input was provided.",
      "i" = "You must supply either:",
      "*" = "{.strong Summary statistics}: provide {.arg success_1}, {.arg n_1}, {.arg success_2}, and {.arg n_2}.",
      "*" = "{.strong Raw data}: provide {.arg formula}, {.arg data}, and {.arg success_level}."
    ))
  }

  # Summary stats + simulation/2SD -- not possible
  if (summary_stat_provided && method %in% c("2SD", "simulation")) {
    cli::cli_abort(c(
      "x" = "The {.val {method}} method is not available when using summary statistics.",
      "i" = "Bootstrap simulation requires the individual data values from both groups.",
      "i" = "Since you only provided summary statistics, there are no individual values to resample from.",
      "i" = "Please either:",
      "*" = "Use {.code method = \"theory\"} with your summary statistics, or",
      "*" = "Provide raw data via {.arg formula} and {.arg data} to use {.val {method}}."
    ))
  }

  # Case 2: Raw data path
  if (formula_provided) {

    if (is.null(data)) {
      cli::cli_abort(c(
        "x" = "You provided {.arg formula} but forgot to provide {.arg data}.",
        "i" = "Please also pass in your data frame. For example:",
        " " = "{.code ci_2prop(formula = Response ~ Group, data = your_data, success_level = \"Yes\")}"
      ))
    }

    if (is.null(formula)) {
      cli::cli_abort(c(
        "x" = "You provided {.arg data} but forgot to provide {.arg formula}.",
        "i" = "The formula should look like: {.code Response ~ Group}",
        "i" = "Where {.code Response} is your outcome variable and {.code Group} defines the two groups."
      ))
    }

    if (is.null(success_level)) {
      cli::cli_abort(c(
        "x" = "You must specify {.arg success_level} when using raw data.",
        "i" = "This tells the function which value of your response variable counts as a success.",
        "i" = "For example, if your variable has values {.val Yes} and {.val No}, use:",
        " " = "{.code success_level = \"Yes\"}"
      ))
    }

    vars <- all.vars(formula)

    if (length(vars) != 2) {
      cli::cli_abort(c(
        "x" = "The formula must have exactly two variables in the form {.code Response ~ Group}.",
        "i" = "You provided: {.code {deparse(formula)}}"
      ))
    }

    response_var <- vars[1]
    group_var    <- vars[2]

    if (!response_var %in% names(data)) {
      cli::cli_abort(c(
        "x" = "The response variable {.val {response_var}} was not found in your data.",
        "i" = "Available variables are: {.val {names(data)}}."
      ))
    }

    if (!group_var %in% names(data)) {
      cli::cli_abort(c(
        "x" = "The grouping variable {.val {group_var}} was not found in your data.",
        "i" = "Available variables are: {.val {names(data)}}."
      ))
    }

    response_col <- data[[response_var]]
    group_col    <- data[[group_var]]

    if (!success_level %in% response_col) {
      cli::cli_abort(c(
        "x" = "The success level {.val {success_level}} was not found in the variable {.val {response_var}}.",
        "i" = "The values present in {.val {response_var}} are: {.val {unique(response_col)}}."
      ))
    }

    group_levels <- unique(na.omit(as.character(group_col)))
    if (length(group_levels) != 2) {
      cli::cli_abort(c(
        "x" = "The grouping variable {.val {group_var}} has {length(group_levels)} unique value(s): {.val {group_levels}}.",
        "i" = "This function requires exactly 2 groups.",
        "i" = "Please filter your data down to just the two groups you want to compare."
      ))
    }

    group_names <- group_levels
    grp1_rows   <- data[as.character(group_col) == group_names[1], ]
    grp2_rows   <- data[as.character(group_col) == group_names[2], ]

    success_1 <- sum(grp1_rows[[response_var]] == success_level, na.rm = TRUE)
    n_1       <- nrow(grp1_rows)
    success_2 <- sum(grp2_rows[[response_var]] == success_level, na.rm = TRUE)
    n_2       <- nrow(grp2_rows)

    cli::cli_inform(c(
      "v" = "Data extracted from {.val {response_var}} ~ {.val {group_var}}:",
      "*" = "{group_names[1]}: {success_1} successes out of {n_1}",
      "*" = "{group_names[2]}: {success_2} successes out of {n_2}",
      "i" = "Success level: {.val {success_level}}"
    ))
  }

  if (is.null(group_names)) group_names <- c("Group 1", "Group 2")

  # ============================================================
  # INPUT VALIDATION
  # ============================================================

  for (val in list(list(success_1, "success_1"), list(success_2, "success_2"))) {
    if (!is.numeric(val[[1]]) || val[[1]] != round(val[[1]]) || val[[1]] < 0) {
      cli::cli_abort(c(
        "x" = "{.arg {val[[2]]}} must be a non-negative whole number.",
        "i" = "You provided: {.val {val[[1]]}}"
      ))
    }
  }

  for (val in list(list(n_1, "n_1"), list(n_2, "n_2"))) {
    if (!is.numeric(val[[1]]) || val[[1]] != round(val[[1]]) || val[[1]] <= 0) {
      cli::cli_abort(c(
        "x" = "{.arg {val[[2]]}} must be a positive whole number.",
        "i" = "You provided: {.val {val[[1]]}}"
      ))
    }
  }

  if (success_1 > n_1) {
    cli::cli_abort(c(
      "x" = "Successes in Group 1 ({success_1}) cannot exceed n_1 ({n_1}).",
      "i" = "Please double-check your values."
    ))
  }

  if (success_2 > n_2) {
    cli::cli_abort(c(
      "x" = "Successes in Group 2 ({success_2}) cannot exceed n_2 ({n_2}).",
      "i" = "Please double-check your values."
    ))
  }

  if (!is.numeric(conf_level) || conf_level <= 0 || conf_level >= 1) {
    cli::cli_abort(c(
      "x" = "{.arg conf_level} must be a number between 0 and 1.",
      "i" = "You provided: {.val {conf_level}}",
      "i" = "Common choices are {.val 0.90}, {.val 0.95}, or {.val 0.99}."
    ))
  }

  if (!method %in% c("2SD", "simulation", "theory")) {
    cli::cli_abort(c(
      "x" = "{.arg method} must be one of {.val 2SD}, {.val simulation}, or {.val theory}.",
      "i" = "You provided: {.val {method}}"
    ))
  }

  if (!is.numeric(sim_reps) || sim_reps < 100) {
    cli::cli_abort(c(
      "x" = "{.arg sim_reps} must be a number of at least 100.",
      "i" = "You provided: {.val {sim_reps}}"
    ))
  }

  # 2SD only valid at 95%
  if (method == "2SD" && conf_level != 0.95) {
    cli::cli_abort(c(
      "x" = "The 2SD method is only valid for 95% confidence intervals.",
      "i" = "You requested a {conf_level * 100}% confidence interval.",
      "i" = "The 2SD method uses a multiplier of 2, which only approximates the correct multiplier at 95% confidence.",
      "i" = "To construct a {conf_level * 100}% confidence interval using simulation, please use:",
      " " = "{.code method = \"simulation\"}"
    ))
  }

  # Compute proportions
  p1_hat   <- success_1 / n_1
  p2_hat   <- success_2 / n_2
  obs_diff <- p1_hat - p2_hat
  fail_1   <- n_1 - success_1
  fail_2   <- n_2 - success_2
  min_cell <- min(success_1, fail_1, success_2, fail_2)

  # Validity warning for theory method
  if (method == "theory" && min_cell < 10) {
    cli::cli_warn(c(
      "!" = "Validity conditions for the theory-based interval may not be met.",
      "i" = "All four cells in the 2x2 table must have at least 10 observations.",
      "i" = "Minimum cell count found: {min_cell}.",
      "i" = "Consider using {.code method = \"2SD\"} or {.code method = \"simulation\"} instead."
    ))
  }

  # ============================================================
  # MATH ENGINE
  # ============================================================

  sim_data <- NULL

  if (method %in% c("2SD", "simulation")) {
    # Independent bootstrap -- resample with replacement from each group
    deck1 <- c(rep(1, success_1), rep(0, fail_1))
    deck2 <- c(rep(1, success_2), rep(0, fail_2))

    sim_data <- replicate(sim_reps, {
      mean(sample(deck1, n_1, replace = TRUE)) -
        mean(sample(deck2, n_2, replace = TRUE))
    })

    se        <- sd(sim_data)
    dist_type <- "Simulated"

    if (method == "2SD") {
      multiplier <- 2
      me         <- multiplier * se
      lower      <- obs_diff - me
      upper      <- obs_diff + me
      calc_type  <- "multiplier"
    } else {
      multiplier <- NA
      me         <- NA
      alpha      <- 1 - conf_level
      lower      <- unname(quantile(sim_data, alpha / 2))
      upper      <- unname(quantile(sim_data, 1 - alpha / 2))
      calc_type  <- "percentile"
    }

  } else {
    # Theory -- unpooled SE (NOT pooled, since we are not assuming pi1 = pi2)
    se         <- sqrt((p1_hat * (1 - p1_hat) / n_1) +
                         (p2_hat * (1 - p2_hat) / n_2))
    multiplier <- abs(qnorm((1 - conf_level) / 2))
    dist_type  <- "Z"
    me         <- multiplier * se
    lower      <- obs_diff - me
    upper      <- obs_diff + me
    calc_type  <- "multiplier"
  }

  # ============================================================
  # BUNDLE INTO S3 OBJECT
  # ============================================================

  res <- list(
    success_1   = success_1, n_1 = n_1, p1_hat = p1_hat,
    success_2   = success_2, n_2 = n_2, p2_hat = p2_hat,
    group_names = group_names,
    obs_diff    = obs_diff,
    min_cell    = min_cell,
    conf_level  = conf_level,
    method      = method,
    calc_type   = calc_type,
    multiplier  = multiplier,
    dist_type   = dist_type,
    se          = se,
    me          = me,
    lower       = lower,
    upper       = upper,
    sim_data    = sim_data
  )

  class(res) <- "stat218_2prop_ci"
  return(res)
}

# ============================================================
# PRINT METHOD
# ============================================================

#' @export
#' @method print stat218_2prop_ci
print.stat218_2prop_ci <- function(x, ...) {
  cli::cli_h1("{x$conf_level * 100}% Confidence Interval for Difference in Proportions ({tools::toTitleCase(x$method)})")
  cli::cli_bullets(c(
    "i" = "{x$group_names[1]}: p-hat1 = {round(x$p1_hat, 4)}  (successes = {x$success_1}, n = {x$n_1})",
    "i" = "{x$group_names[2]}: p-hat2 = {round(x$p2_hat, 4)}  (successes = {x$success_2}, n = {x$n_2})",
    "i" = "Point Estimate (p-hat1 - p-hat2): {round(x$obs_diff, 4)}",
    "i" = "SD of Sampling Distribution: {round(x$se, 4)}",
    "*" = "Interval: ({round(x$lower, 4)}, {round(x$upper, 4)})"
  ))

  if (x$method == "theory" && x$min_cell < 10) {
    cli::cli_warn(c(
      "!" = "Validity conditions may not be met -- at least one cell has fewer than 10 observations.",
      "i" = "Minimum cell count: {x$min_cell}.",
      "i" = "Consider using {.code method = \"2SD\"} or {.code method = \"simulation\"}."
    ))
  }

  invisible(x)
}

# ============================================================
# PLOT METHOD
# ============================================================

#' @export
#' @method plot stat218_2prop_ci
plot.stat218_2prop_ci <- function(x, ...) {

  x_label   <- paste0("Difference in Sample Proportions (",
                      x$group_names[1], " - ", x$group_names[2], ")")
  pct_label <- paste0(x$conf_level * 100, "%")

  # ---- Beautified gt contingency table ----
  ct_data <- data.frame(
    Group   = c(x$group_names[1], x$group_names[2], "Total"),
    Success = c(x$success_1, x$success_2, x$success_1 + x$success_2),
    Failure = c(x$n_1 - x$success_1, x$n_2 - x$success_2,
                (x$n_1 - x$success_1) + (x$n_2 - x$success_2)),
    Total   = c(x$n_1, x$n_2, x$n_1 + x$n_2)
  )

  gt_table <- gt::gt(ct_data) |>
    gt::tab_header(title = "Observed 2x2 Contingency Table") |>
    gt::cols_label(
      Group   = "",
      Success = "Success",
      Failure = "Failure",
      Total   = "Total"
    ) |>
    gt::tab_style(
      style     = gt::cell_fill(color = "#2C3E50"),
      locations = gt::cells_column_labels()
    ) |>
    gt::tab_style(
      style     = gt::cell_text(color = "white", weight = "bold"),
      locations = gt::cells_column_labels()
    ) |>
    gt::tab_style(
      style     = gt::cell_text(weight = "bold"),
      locations = gt::cells_body(columns = Group)
    ) |>
    gt::tab_style(
      style     = gt::cell_fill(color = "#F4F6F7"),
      locations = gt::cells_body(rows = 3)
    ) |>
    gt::tab_style(
      style     = gt::cell_text(weight = "bold"),
      locations = gt::cells_body(rows = 3)
    ) |>
    gt::tab_style(
      style     = gt::cell_borders(sides = "top", color = "#2C3E50",
                                   weight = gt::px(2)),
      locations = gt::cells_body(rows = 3)
    ) |>
    gt::cols_align(align = "center",
                   columns = c(Success, Failure, Total)) |>
    gt::tab_options(
      table.font.size         = gt::px(13),
      table.width             = gt::pct(90),
      heading.title.font.size = gt::px(13),
      heading.align           = "center"
    )

  gt_grob <- gt::as_gtable(gt_table)
  p_table <- ggplot2::ggplot() +
    ggplot2::annotation_custom(gt_grob) +
    ggplot2::theme_void()

  # ---- Forest Plot ----
  p_forest <- ggplot2::ggplot() +
    ggplot2::geom_segment(
      ggplot2::aes(x = x$lower, xend = x$upper, y = 0, yend = 0),
      linewidth = 2, color = "#2C3E50") +
    ggplot2::geom_point(
      ggplot2::aes(x = x$obs_diff, y = 0),
      size = 6, color = "#D55E00") +
    ggplot2::geom_text(
      ggplot2::aes(x = x$lower, y = -0.4, label = round(x$lower, 4)),
      size = 5, color = "#2C3E50") +
    ggplot2::geom_text(
      ggplot2::aes(x = x$upper, y = -0.4, label = round(x$upper, 4)),
      size = 5, color = "#2C3E50") +
    ggplot2::geom_text(
      ggplot2::aes(x = x$obs_diff, y = 0.4,
                   label = paste("Difference =", round(x$obs_diff, 4))),
      size = 5, fontface = "bold") +
    ggplot2::scale_y_continuous(limits = c(-1, 1)) +
    ggplot2::labs(
      title = paste0(pct_label, " Confidence Interval"),
      x = x_label, y = "") +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      axis.text.y        = ggplot2::element_blank(),
      axis.ticks.y       = ggplot2::element_blank(),
      panel.grid.minor.y = ggplot2::element_blank(),
      panel.grid.major.y = ggplot2::element_blank()
    )

  if (x$calc_type == "multiplier") {
    mid_left  <- (x$lower + x$obs_diff) / 2
    mid_right <- (x$obs_diff + x$upper) / 2
    me_label  <- paste("ME =", round(x$me, 4))
    p_forest  <- p_forest +
      ggplot2::geom_text(
        ggplot2::aes(x = mid_left,  y = 0.3, label = me_label),
        size = 4.5, color = "#555555") +
      ggplot2::geom_text(
        ggplot2::aes(x = mid_right, y = 0.3, label = me_label),
        size = 4.5, color = "#555555")
  } else {
    p_forest <- p_forest +
      ggplot2::geom_text(
        ggplot2::aes(x = x$obs_diff, y = 0.7,
                     label = "Bounds found via Percentiles"),
        size = 4.5, color = "#555555", fontface = "italic")
  }

  # ---- Distribution Plot ----
  if (x$method %in% c("2SD", "simulation")) {

    plot_data       <- data.frame(sim = x$sim_data)
    plot_data$in_ci <- plot_data$sim >= x$lower & plot_data$sim <= x$upper
    ci_mid          <- (x$lower + x$upper) / 2
    y_label_pos     <- max(table(cut(x$sim_data, breaks = 40))) * 0.5

    p_dist <- ggplot2::ggplot(plot_data,
                              ggplot2::aes(x = sim, fill = in_ci)) +
      ggplot2::geom_histogram(color = "white", bins = 40, boundary = 0) +
      ggplot2::geom_vline(xintercept = c(x$lower, x$upper),
                          color = "black", linetype = "dashed",
                          linewidth = 1) +
      ggplot2::annotate("text",
                        x = x$lower, y = Inf, label = round(x$lower, 4),
                        vjust = 2, hjust = 1.1, size = 4.5) +
      ggplot2::annotate("text",
                        x = x$upper, y = Inf, label = round(x$upper, 4),
                        vjust = 2, hjust = -0.1, size = 4.5) +
      ggplot2::annotate("text",
                        x = ci_mid, y = y_label_pos, label = pct_label,
                        size = 7, fontface = "bold", color = "#2C3E50") +
      ggplot2::scale_fill_manual(
        values = c("FALSE" = "gray80", "TRUE" = "#3498DB")) +
      ggplot2::labs(
        title    = "Bootstrap Distribution (Independent Resampling)",
        subtitle = paste0("Centered at Observed Difference = ",
                          round(x$obs_diff, 4)),
        x = x_label, y = "Count") +
      ggplot2::theme_minimal() +
      ggplot2::theme(legend.position = "none")

  } else {
    val <- dens <- sim <-  NA

    x_vals    <- seq(x$obs_diff - 4 * x$se, x$obs_diff + 4 * x$se,
                     length.out = 1000)
    y_vals    <- dnorm(x_vals, mean = x$obs_diff, sd = x$se)
    plot_data <- data.frame(val = x_vals, dens = y_vals)
    ci_mid    <- (x$lower + x$upper) / 2
    y_label_pos <- max(y_vals) * 0.5

    p_dist <- ggplot2::ggplot(plot_data,
                              ggplot2::aes(x = val, y = dens)) +
      ggplot2::geom_line(linewidth = 1) +
      ggplot2::geom_area(
        data = subset(plot_data, val >= x$lower & val <= x$upper),
        fill = "#3498DB", alpha = 0.5) +
      ggplot2::geom_vline(xintercept = c(x$lower, x$upper),
                          color = "black", linetype = "dashed",
                          linewidth = 1) +
      ggplot2::annotate("text",
                        x = x$lower, y = Inf, label = round(x$lower, 4),
                        vjust = 2, hjust = 1.1, size = 4.5) +
      ggplot2::annotate("text",
                        x = x$upper, y = Inf, label = round(x$upper, 4),
                        vjust = 2, hjust = -0.1, size = 4.5) +
      ggplot2::annotate("text",
                        x = ci_mid, y = y_label_pos, label = pct_label,
                        size = 7, fontface = "bold", color = "#2C3E50") +
      ggplot2::labs(
        title    = "Theoretical Normal Distribution (Z-Curve)",
        subtitle = paste0("Centered at Observed Difference = ",
                          round(x$obs_diff, 4)),
        x = x_label, y = "Density") +
      ggplot2::theme_minimal() +
      ggplot2::theme(
        axis.text.y  = ggplot2::element_blank(),
        axis.ticks.y = ggplot2::element_blank()
      )
  }

  # Validity caption
  if (x$method == "theory" && x$min_cell < 10) {
    p_dist <- p_dist +
      ggplot2::labs(caption = paste0(
        "Warning: at least one cell has fewer than 10 observations. ",
        "Validity conditions may not be met."
      )) +
      ggplot2::theme(
        plot.caption = ggplot2::element_text(
          color = "#C0392B", face = "bold", size = 9, hjust = 0
        )
      )
  }

  return(
    p_dist / p_forest / p_table +
      patchwork::plot_layout(heights = c(2.5, 1, 1.5))
  )
}

# ============================================================
# PLOT_STEPS METHOD -- 3-panel patchwork
# ============================================================

#' @export
#' @method plot_steps stat218_2prop_ci
plot_steps.stat218_2prop_ci <- function(x, ...) {

  pct <- x$conf_level * 100

  # Validity warning -- top of bottom panel
  warning_text <- ""
  if (x$method == "theory" && x$min_cell < 10) {
    warning_text <- paste0(
      "<span style='color:#C0392B; font-size:12pt;'><b>&#9888; Validity Condition Warning:</b> ",
      "At least one cell in the 2x2 table has fewer than 10 observations. ",
      "Consider rerunning with simulation method for more reliable results.</span><br><br>"
    )
  }

  # ---- Build method-specific blurb and equations ----
  if (x$method == "2SD") {
    method_blurb <- paste0(
      "We use the <b>2SD Method</b>. An independent bootstrap is generated ",
      "by resampling with replacement from each group separately.<br>",
      "&bull; SD of Sampling Distribution = ", round(x$se, 4), "<br>",
      "&bull; Multiplier = 2 (standard for 95% confidence)<br><br>",
      "<i>The formula and calculation are shown below:</i>"
    )
    tex_formula <- latex2exp::TeX(
      r"($ME = Multiplier \times SD(\hat{p}_1 - \hat{p}_2)$)",
      output = "character"
    )
    tex_calc <- latex2exp::TeX(
      paste0("$ME = 2 \\times ", round(x$se, 4),
             " = ", round(x$me, 4), "$"),
      output = "character"
    )
    use_math_panel <- TRUE

  } else if (x$method == "simulation") {
    method_blurb <- paste0(
      "We use the <b>Bootstrap Simulation Method</b>. Same independent ",
      "bootstrap as the 2SD method, but instead of a multiplier, we take ",
      "the middle ", pct, "% of the simulated distribution directly:<br>",
      "&bull; Lower Bound = ", (1 - x$conf_level) / 2 * 100,
      "th percentile = <b>", round(x$lower, 4), "</b><br>",
      "&bull; Upper Bound = ", (1 - (1 - x$conf_level) / 2) * 100,
      "th percentile = <b>", round(x$upper, 4), "</b>"
    )
    use_math_panel <- FALSE

  } else {
    method_blurb <- paste0(
      "We use the <b>Theory-Based Method</b> with an <b>unpooled</b> ",
      "standard error. Unlike the hypothesis test, we do not assume ",
      "&pi;<sub>1</sub> = &pi;<sub>2</sub> here, so each group's proportion ",
      "is used separately in the formula.<br>",
      "&bull; SD of Sampling Distribution = &radic;(p&#770;<sub>1</sub>(1 &minus; p&#770;<sub>1</sub>)/n<sub>1</sub> + p&#770;<sub>2</sub>(1 &minus; p&#770;<sub>2</sub>)/n<sub>2</sub>)",
      " = ", round(x$se, 4), "<br>",
      "&bull; Multiplier = ", round(x$multiplier, 3),
      " (from the Z-distribution for ", pct, "% confidence)<br><br>",
      "<i>The formula and calculation are shown below:</i>"
    )
    tex_formula <- latex2exp::TeX(
      r"($ME = Multiplier \times \sqrt{\frac{\hat{p}_1(1 - \hat{p}_1)}{n_1} + \frac{\hat{p}_2(1 - \hat{p}_2)}{n_2}}$)",
      output = "character"
    )
    tex_calc <- latex2exp::TeX(
      paste0("$ME = ", round(x$multiplier, 3),
             " \\times \\sqrt{\\frac{", round(x$p1_hat, 4),
             "(1 - ", round(x$p1_hat, 4), ")}{", x$n_1,
             "} + \\frac{", round(x$p2_hat, 4),
             "(1 - ", round(x$p2_hat, 4), ")}{", x$n_2,
             "}} = ", round(x$me, 4), "$"),
      output = "character"
    )
    use_math_panel <- TRUE
  }

  # ---- PANEL 1: Top HTML ----
  top_html <- paste0(
    "<span style='font-size:20pt; color:#2C3E50;'><b>Confidence Interval Construction</b></span><br><br>",

    "<span style='font-size:14pt;'><b>1. The Data</b></span><br>",
    "&bull; <b>", x$group_names[1], ":</b> p&#770;<sub>1</sub> = ",
    round(x$p1_hat, 4), " (", x$success_1, " successes out of n = ",
    x$n_1, ")<br>",
    "&bull; <b>", x$group_names[2], ":</b> p&#770;<sub>2</sub> = ",
    round(x$p2_hat, 4), " (", x$success_2, " successes out of n = ",
    x$n_2, ")<br>",
    "&bull; <b>Point Estimate (p&#770;<sub>1</sub> &minus; p&#770;<sub>2</sub>):</b> ",
    round(x$obs_diff, 4), "<br><br>",

    "<span style='font-size:14pt;'><b>2. The Margin of Error</b></span><br>",
    method_blurb
  )

  p_top <- ggplot2::ggplot() +
    ggtext::geom_textbox(
      ggplot2::aes(x = 0, y = 1, label = top_html),
      width = ggplot2::unit(0.95, "npc"),
      hjust = 0, vjust = 1,
      box.color = NA, fill = NA,
      size = 5, lineheight = 1.5
    ) +
    ggplot2::coord_cartesian(xlim = c(0, 1), ylim = c(-0.8, 1)) +
    ggplot2::theme_void() +
    ggplot2::theme(plot.margin = ggplot2::margin(t = 20, r = 20, b = 0, l = 20))

  # ---- PANEL 2: Math equations ----
  if (use_math_panel) {
    p_math_data <- data.frame(
      x     = c(0.1, 0.1),
      y     = c(4.0, 0),
      label = c(tex_formula, tex_calc)
    )
    p_math <- ggplot2::ggplot(p_math_data,
                              ggplot2::aes(x = x, y = y, label = label)) +
      ggplot2::geom_text(parse = TRUE, size = 6, hjust = 0) +
      ggplot2::coord_cartesian(xlim = c(0, 1), ylim = c(-2.0, 6.5),
                               clip = "off") +
      ggplot2::theme_void() +
      ggplot2::theme(plot.margin = ggplot2::margin(t = 10, r = 20,
                                                   b = 10, l = 40))
  } else {
    p_math <- ggplot2::ggplot() + ggplot2::theme_void()
  }

  # ---- PANEL 3: Bottom HTML -- warning at top ----
  if (x$calc_type == "multiplier") {
    interval_html <- paste0(
      "<b>Confidence Interval</b> = (p&#770;<sub>1</sub> &minus; p&#770;<sub>2</sub>) &plusmn; ME<br>",
      "CI = ", round(x$obs_diff, 4), " &plusmn; ", round(x$me, 4),
      " &rarr; <b>(", round(x$lower, 4), ", ", round(x$upper, 4), ")</b>"
    )
  } else {
    interval_html <- paste0(
      "<b>Confidence Interval: (",
      round(x$lower, 4), ", ", round(x$upper, 4), ")</b>"
    )
  }

  bottom_html <- paste0(
    warning_text,
    "<span style='font-size:14pt;'><b>3. The Interval</b></span><br>",
    interval_html, "<br><br>",
    "<i>Practical Interpretation:</i> We are ", pct,
    "% confident that the true difference in population proportions (&pi;<sub>1</sub> &minus; &pi;<sub>2</sub>) is between ",
    round(x$lower, 4), " and ", round(x$upper, 4), ".<br>",
    "<i>Frequentist Interpretation:</i> If we were to take 100 random ",
    "samples and calculate a confidence interval for each, we would expect ",
    "approximately ", pct, " of those intervals to contain the true ",
    "difference in population proportions."
  )

  p_bottom <- ggplot2::ggplot() +
    ggtext::geom_textbox(
      ggplot2::aes(x = 0, y = 1, label = bottom_html),
      width = ggplot2::unit(0.95, "npc"),
      hjust = 0, vjust = 1,
      box.color = NA, fill = NA,
      size = 5, lineheight = 1.5
    ) +
    ggplot2::coord_cartesian(xlim = c(0, 1), ylim = c(-0.15, 1)) +
    ggplot2::theme_void() +
    ggplot2::theme(plot.margin = ggplot2::margin(t = 0, r = 20,
                                                 b = 20, l = 20))

  if (use_math_panel) {
    return(
      p_top / p_math / p_bottom +
        patchwork::plot_layout(heights = c(2.6, 1.8, 3.2))
    )
  } else {
    return(
      p_top / p_bottom +
        patchwork::plot_layout(heights = c(3, 2))
    )
  }
}
